{% set name = "lcensemble" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lcensemble-{{ version }}.tar.gz
  sha256: 7762a2240d73ea0030db4d36322613923d101b22b22c7fde48d870ac65a369b4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - hyperopt ==0.2.7
    - lightgbm ==3.3.5
    - numpy ==1.23.3
    - pandas ==1.5.0
    - scikit-learn ==1.1.2
    - xgboost ==1.6.2

test:
  imports:
    - lce

about:
  home: https://lce.readthedocs.io/en/latest/
  summary: Local Cascade Ensemble package
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - LocalCascadeEnsemble
